"""Slurm job script generation.

Generates a shell script that runs on an Iris compute node. All environment
setup (module load, conda, pip) and the user command are embedded in the
script; the access node only uploads and submits it.
"""

import os
import shlex
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .config import Config
from .env_manager import EnvironmentManager


class JobScriptBuilder:
    """Build a UL HPC Slurm batch script."""

    def __init__(
        self,
        config: Config,
        command: List[str],
        project_dir: str,
        remote_dir: str,
        env_manager: Optional[EnvironmentManager] = None,
        job_name: Optional[str] = None,
        partition: Optional[str] = None,
        nodes: Optional[int] = None,
        ntasks: Optional[int] = None,
        cpus_per_task: Optional[int] = None,
        mem: Optional[str] = None,
        time: Optional[str] = None,
        gpus: Optional[int] = None,
        conda_env: Optional[str] = None,
        container: Optional[str] = None,
        runtime_modules: Optional[List[str]] = None,
        python_executable: Optional[str] = None,
        use_conda: Optional[bool] = None,
    ):
        self.config = config
        self.command = command
        self.project_dir = Path(project_dir)
        self.remote_dir = remote_dir
        self.env_manager = env_manager or EnvironmentManager(
            project_dir,
            conda_module=config.conda_module,
            python_module=config.python_module,
            conda_env=conda_env,
            runtime_modules=runtime_modules if runtime_modules is not None else config.runtime_modules,
            python_executable=python_executable or config.python_executable,
            use_conda=config.use_conda if use_conda is None else use_conda,
        )
        self.job_name = job_name or self.project_dir.name or "ulhpc_job"
        self.partition = partition or config.default_partition
        self.nodes = nodes or config.default_nodes
        self.ntasks = ntasks or config.default_ntasks
        self.cpus_per_task = cpus_per_task or config.default_cpus_per_task
        self.mem = mem or config.default_mem
        self.time = time or config.default_time
        self.gpus = gpus or 0
        self.container = container
        self.python_executable = python_executable or config.python_executable

    def _command_for_runtime(self) -> List[str]:
        """Apply runtime-level command rewrites without changing user args."""
        if not self.command:
            return []
        first = Path(str(self.command[0])).name
        if self.python_executable and first in {"python", "python3"}:
            return [self.python_executable, *self.command[1:]]
        return self.command

    def build(self) -> str:
        """Return the full Slurm script as a string."""
        now = datetime.now().isoformat(timespec="seconds")
        runtime_command = self._command_for_runtime()
        user_cmd = " ".join(shlex.quote(str(arg)) for arg in runtime_command)

        if self.container:
            env_block = self._container_block()
            # If the user already provided a full apptainer command, run it as-is.
            if runtime_command and runtime_command[0] in ("apptainer", "singularity"):
                wrapped_cmd = user_cmd
            else:
                wrapped_cmd = f"apptainer exec {shlex.quote(self.container)} {user_cmd}"
        else:
            env_block = self.env_manager.build_env_block()
            wrapped_cmd = user_cmd

        lines: List[str] = [
            "#!/bin/bash -l",
            "# This script was generated by ulhpc-submit",
            f"# Generated at: {now}",
            "",
            f"#SBATCH --job-name={self.job_name}",
            f"#SBATCH --partition={self.partition}",
            f"#SBATCH --nodes={self.nodes}",
            f"#SBATCH --ntasks-per-node={self.ntasks}",
            f"#SBATCH --cpus-per-task={self.cpus_per_task}",
            f"#SBATCH --mem={self.mem}",
            f"#SBATCH --time={self.time}",
            "#SBATCH --output=job_%j.out",
            "#SBATCH --error=job_%j.err",
            f"#SBATCH --chdir={self.remote_dir}",
        ]

        if self.gpus > 0:
            lines.append(f"#SBATCH --gres=gpu:{self.gpus}")

        lines.extend([
            "",
            "set -uo pipefail",
            'echo "[ulhpc-submit] job started at $(date)"',
            f'echo "[ulhpc-submit] running on host: $(hostname)"',
            f'echo "[ulhpc-submit] remote dir: {self.remote_dir}"',
            "",
            env_block,
            "",
            'echo "[ulhpc-submit] executing user command"',
            f"set +e",
            f"{wrapped_cmd}",
            "exit_code=$?",
            "set -e",
            f'echo "[ulhpc-submit] exit_code=$exit_code"',
            f'echo "[ulhpc-submit] job finished at $(date)"',
            "exit $exit_code",
        ])

        return "\n".join(lines) + "\n"

    def _container_block(self) -> str:
        """Generate an Apptainer/Singularity setup block."""
        module = getattr(self.config, "container_module", "apptainer")
        lines = [
            'echo "[ulhpc-submit] configuring container environment on compute node"',
            f"module load {module}",
            f'echo "[ulhpc-submit] container: {self.container}"',
            f'export APPTAINER_CONTAINER="{self.container}"',
        ]
        return "\n".join(lines)

    def write(self, path: Optional[str] = None) -> str:
        """Write script to a local path and return that path."""
        if path is None:
            local_staging = Path(self.project_dir) / ".ulhpc_submit"
            local_staging.mkdir(parents=True, exist_ok=True)
            path = str(local_staging / "generated_job.sh")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.build())
        os.chmod(path, 0o755)
        return path
